function(command_library lib_name target_name)
    SET(target infrared.commands.${lib_name})
    SET(${target_name} ${target} PARENT_SCOPE)
    add_library(${target} MODULE ${ARGN})
    set_target_properties(${target} PROPERTIES PREFIX "")
    set_target_properties(${target} PROPERTIES OUTPUT_NAME "commands.${lib_name}")
    set_target_properties(${target} PROPERTIES SUFFIX ".dll")
endfunction()